version: '3'
services:

  pg:
    image: postgres
    restart: always
    ports:
      - "15432:5432"

    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=test_db