version: '3'
services:

  pg:
    image: postgres
    restart: always
    ports:
      - "25432:5432"

    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test_db